### ISSUE TITLE
Decoding `metav1.List` Kubernetes types from YAML will panic

### ISSUE THREAD

**Issue by slok** [slok/kahoy#88]
At this moment we are only unmarshalling regular objects, our code will panic if tries decoding a [`metav1.List`](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#List) object. We should be able to handle this correctly. These are the object YAML style:

```yaml
apiVersion: v1                                                                                            
kind: List
items: []
```
