### ISSUE TITLE
Empty YAMLs on multiresource YAML files can't be parsed

### ISSUE THREAD

**Issue by slok** [slok/kahoy#94]
On multi-resource YAML files that start with comments or are empty, YAML parsing fails. Example:

```yaml
# some comment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
---
...
```
Parsing this file fails (probably because of `# some comment`).
